### ISSUE TITLE
Catlet VMs are not exportable in Hyper-V

### ISSUE THREAD

**Issue by ChristopherMann** [eryph-org/eryph#123]
VMs which were created with eryph cannot be exported with Hyper-V tools.

Replication procedure:
1. Create a new catlet VM with `New-Catlet -Parent ... -Name myvm`
2. Export the created VM in Hyper-V with: `Export-VM -Name myvm -Path ...`

The export fails with an error message like this:
```
Export-VM: Failed to copy file during export.

Failed to copy file from '...' to '...': The file exists. (0x80070050).
```

[AB#579](https://dev.azure.com/dbosoft/eae53133-585f-4d55-8e1f-5cba6fd8ce3b/_workitems/edit/579)

**Comment by fw2568** [comment]
Proposal: when genes are extracted the filename is replaced by the first 10 chars the gene hash (like in a git commit). During attach the name reference (sda, sdb) has to be replaced with the hash part by lookup of gene hash from metadata.
