### ISSUE TITLE
Driver upgrade creates duplicated overlay switch

### ISSUE THREAD

**Issue by fw2568** [eryph-org/eryph#169]
After upgrading the driver it could happen that 2 switches are created as overlay switch. Both have the extension enabled. 

![image](https://github.com/eryph-org/eryph/assets/5318218/2c82e518-fd51-4303-bf3b-acde0793c832)

[AB#657](https://dev.azure.com/dbosoft/eae53133-585f-4d55-8e1f-5cba6fd8ce3b/_workitems/edit/657)

**Comment by ChristopherMann** [comment]
The issue can be replicated without updating the driver as follows:

1. Stop eryph
2. Disable the OVN extension on the eryph_overlay switch
3. Start eryph again

During the startup, eryph will create an additional eryph_overlay switch.
