### ISSUE TITLE
New certificate is added to the certificate store on each start

### ISSUE THREAD

**Issue by ChristopherMann** [eryph-org/eryph#239]
eryph-zero adds a new token signing certificate (eryph-identity) to the certificate store on each start and instead of reusing the existing certificate. The old certificates are also not removed which pollutes the certificate store.

[AB#697](https://dev.azure.com/dbosoft/eae53133-585f-4d55-8e1f-5cba6fd8ce3b/_workitems/edit/697)

**Comment by fw2568** [comment]
confirmed, added to milestone

**Comment by fw2568** [comment]
questions is also why token signing cert has to be added to store at all, looks to be something that broke with the switch to openiddict.

**Comment by fw2568** [comment]
mmh, ok, blame author of #70 , seems to be necessary to be in store.

**Comment by fw2568** [comment]
@ChristopherMann  as discussed - when looking at this issue - check if removing the ca certificate is a option, so we add only the ssl certificate self signed to computer store for local access and export the public cert for remote SSL users.
