### ISSUE TITLE
Errors during uninstallation

### ISSUE THREAD

**Issue by fw2568** [eryph-org/eryph#251]
When eryph-zero is uninstalled with "Remove-Configuration" this error occurs on some systems:

[15:11:14 INF] Removing data files...
[15:11:14 ERR] Uninstallation failed. Error: Access to the path 'user-data' is denied.

[AB#706](https://dev.azure.com/dbosoft/eae53133-585f-4d55-8e1f-5cba6fd8ce3b/_workitems/edit/706)

**Comment by ChristopherMann** [comment]
I already fixed the specific issue in #254. The uninstallation now just logs a warning and continues. Anyway, I have reviewed the error handling of the uninstallation and created #286 which fixes another gap in the uninstaller.
