### ISSUE TITLE
Concurrent gene requests: no progress on waiting tasks

### ISSUE THREAD

**Issue by fw2568** [eryph-org/eryph#93]
If multiple tasks requesting a gene, the waiting tasks don't report any progress if the first request is resolving a dependend gene.

Example:
first task: parent -> child -> required genes => waiting for required gene and reporting
second task: parent -> task keeps running and waiting for parent to be resolved

The task handling is implemented in GeneRequestRegistry. Here we should add a logic to inform other tasks that we are already resolved parent to child and register it as additional listeners for the dependend activitites.

[AB#574](https://dev.azure.com/dbosoft/eae53133-585f-4d55-8e1f-5cba6fd8ce3b/_workitems/edit/574)

**Comment by ChristopherMann** [comment]
This has been resolved in scope of #214. We now only queue download requests for fully resolved genes which ensures that the download progress is properly updated for all waiting tasks.
